version: 2
updates:
  - package-ecosystem: cargo
    directory: /tools
    schedule:
      interval: weekly
    groups:
      rust-deps:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
