// SPDX-License-Identifier: GPL-2.0-only
#include "bc5/policy.hpp"

#include "policy_tsv.hpp" // generated by CMake from backend/policy/pm4-policy.tsv

#include <charconv>
#include <stdexcept>
#include <string>

namespace bc5::policy {

namespace {

bool parse_hex(std::string_view s, std::uint32_t &out) {
    while (!s.empty() && (s.front() == ' ' || s.front() == '\t')) s.remove_prefix(1);
    while (!s.empty() && (s.back() == ' ' || s.back() == '\t' || s.back() == '\r')) s.remove_suffix(1);
    if (s.starts_with("0x") || s.starts_with("0X")) s.remove_prefix(2);
    if (s.empty()) return false;
    auto r = std::from_chars(s.data(), s.data() + s.size(), out, 16);
    return r.ec == std::errc{} && r.ptr == s.data() + s.size();
}

bool parse_verdict(std::string_view s, Verdict &v) {
    while (!s.empty() && s.back() == '\r') s.remove_suffix(1);
    if (s == "pass") v = Verdict::Pass;
    else if (s == "rewrite") v = Verdict::Rewrite;
    else if (s == "drop") v = Verdict::Drop;
    else return false;
    return true;
}

std::vector<std::string_view> split_tabs(std::string_view line) {
    std::vector<std::string_view> cols;
    while (true) {
        auto tab = line.find('\t');
        if (tab == std::string_view::npos) {
            cols.push_back(line);
            break;
        }
        cols.push_back(line.substr(0, tab));
        line.remove_prefix(tab + 1);
    }
    return cols;
}

// SET_CONFIG_REG, SET_CONTEXT_REG, SET_SH_REG, SET_UCONFIG_REG, SET_SH_REG_INDEX: dword1 = offset.
bool is_plain_set(std::uint8_t op, std::uint32_t &base) {
    switch (op) {
    case 0x68: base = 0x2000; return true;
    case 0x69: base = 0xa000; return true;
    case 0x76:
    case 0x9b: base = 0x2c00; return true;
    case 0x79: base = 0xc000; return true;
    default: return false;
    }
}

constexpr std::uint32_t kMmComputeStaticThreadMgmtSe0 = 0x2e16;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe1 = 0x2e17;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe2 = 0x2e19;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe3 = 0x2e1a;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Ps = 0x2c07;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Vs = 0x2c47;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Gs = 0x2c87;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Hs = 0x2d07;

} // namespace

bool is_draw_or_dispatch(std::uint8_t opcode) {
    switch (opcode) {
    case 0x15: // DISPATCH_DIRECT
    case 0x16: // DISPATCH_INDIRECT
    case 0x25: // DRAW_INDEX_INDIRECT
    case 0x27: // DRAW_INDEX_2
    case 0x2d: // DRAW_INDEX_AUTO
    case 0x35: // DRAW_INDEX_OFFSET_2
    case 0x38: // DRAW_INDEX_MULTI_AUTO
    case 0x24: // DRAW_INDIRECT
        return true;
    default:
        return false;
    }
}

const char *verdict_name(Verdict v) {
    switch (v) {
    case Verdict::Pass: return "pass";
    case Verdict::Rewrite: return "rewrite";
    case Verdict::Split: return "split";
    case Verdict::Drop: return "drop";
    }
    return "?";
}

Policy Policy::parse(std::string_view tsv) {
    Policy p;
    for (auto &v : p.ops_) v = Verdict::Drop;
    std::size_t line_no = 0;
    while (!tsv.empty()) {
        ++line_no;
        auto nl = tsv.find('\n');
        std::string_view line = tsv.substr(0, nl);
        tsv = nl == std::string_view::npos ? std::string_view{} : tsv.substr(nl + 1);
        if (!line.empty() && line.back() == '\r') line.remove_suffix(1);
        if (line.empty() || line.front() == '#') continue;
        auto cols = split_tabs(line);
        auto bad = [&](const char *what) {
            throw std::invalid_argument("pm4-policy.tsv line " + std::to_string(line_no) + ": " +
                                        what);
        };
        Verdict v{};
        if (cols[0] == "default-op" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.default_op_ = v;
        } else if (cols[0] == "default-reg" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.default_reg_ = v;
        } else if (cols[0] == "type0" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.type0_ = v;
        } else if (cols[0] == "op" && cols.size() >= 3) {
            std::uint32_t op = 0;
            if (!parse_hex(cols[1], op) || op > 0xff) bad("opcode");
            if (!parse_verdict(cols[2], v)) bad("verdict");
            p.ops_[op] = v;
            p.op_set_[op] = true;
        } else if (cols[0] == "reg" && cols.size() >= 3) {
            std::uint32_t a = 0, b = 0;
            auto dash = cols[1].find('-');
            if (dash == std::string_view::npos) {
                if (!parse_hex(cols[1], a)) bad("register");
                b = a;
            } else if (!parse_hex(cols[1].substr(0, dash), a) ||
                       !parse_hex(cols[1].substr(dash + 1), b)) {
                bad("register");
            }
            if (!parse_verdict(cols[2], v)) bad("verdict");
            p.regs_.push_back({a, b, v});
        } else {
            bad("unknown kind");
        }
    }
    return p;
}

const Policy &Policy::builtin() {
    static const Policy p = Policy::parse(kPolicyTsv);
    return p;
}

Verdict Policy::op(std::uint8_t opcode) const {
    return op_set_[opcode] ? ops_[opcode] : default_op_;
}

Verdict Policy::reg(std::uint32_t mm) const {
    for (const auto &r : regs_) {
        if (mm >= r.first && mm <= r.last) return r.verdict;
    }
    return default_reg_;
}

Verdict Policy::packet(const std::uint32_t *p, std::uint32_t len) const {
    const std::uint32_t header = p[0];
    const std::uint32_t type = header >> 30;
    if (type == 2) return Verdict::Pass;
    if (type == 0) return type0_;
    if (type == 1) return Verdict::Drop;
    const auto opcode = static_cast<std::uint8_t>((header >> 8) & 0xff);
    const Verdict ov = op(opcode);
    std::uint32_t base = 0;
    if (ov != Verdict::Pass || !is_plain_set(opcode, base) || len < 2) return ov;
    const std::uint32_t offset = p[1] & 0xffff;
    bool seen = false;
    Verdict first{};
    for (std::uint32_t i = 0; i + 2 < len; ++i) {
        const Verdict rv = reg(base + offset + i);
        if (!seen) {
            first = rv;
            seen = true;
        } else if (rv != first) {
            return Verdict::Split;
        }
    }
    return seen ? first : Verdict::Pass;
}

std::size_t filter(const Policy &policy, std::span<const std::uint32_t> src,
                   std::span<std::uint32_t> out, const FilterOptions &opt, FilterStats &stats) {
    const std::size_t n = src.size();
    std::size_t i = 0;
    while (i < n) {
        const std::uint32_t header = src[i];
        const std::uint32_t type = header >> 30;
        std::uint32_t len = 1;
        if (type == 0 || type == 3) {
            const std::uint32_t count = (header >> 16) & 0x3fff;
            len = count == 0x3fff ? 1 : count + 2;
        } else if (type == 1) {
            len = 1;
        }
        stats.packets++;
        stats.dwords += len;
        if (i + len > n) {
            // A packet running past the end: NOP the remainder, the CP must not read past it.
            stats.truncated++;
            for (std::size_t k = i; k < n; ++k) out[k] = kNop;
            stats.dwords_dropped += n - i;
            i = n;
            break;
        }
        Verdict v = policy.packet(&src[i], len);
        if (opt.drop_draws && type == 3 &&
            is_draw_or_dispatch(static_cast<std::uint8_t>((header >> 8) & 0xff))) {
            v = Verdict::Drop;
        }
        switch (v) {
        case Verdict::Drop:
            for (std::uint32_t k = 0; k < len; ++k) out[i + k] = kNop;
            stats.dropped++;
            stats.dwords_dropped += len;
            break;
        case Verdict::Pass:
        case Verdict::Rewrite:
        case Verdict::Split: {
            for (std::uint32_t k = 0; k < len; ++k) out[i + k] = src[i + k];
            if (v == Verdict::Pass) stats.passed++;
            else if (v == Verdict::Rewrite) stats.rewritten++;
            else stats.split++;
            if (type != 3) break;
            const auto opcode = static_cast<std::uint8_t>((header >> 8) & 0xff);
            if ((opcode == kOpReleaseMem || opcode == kOpEventWriteEop) && opt.clear_int_sel &&
                len >= 4) {
                // RELEASE_MEM: data_cntl is dword 2; EVENT_WRITE_EOP: dword 3. INT_SEL = bits 25:24.
                const std::uint32_t dc = opcode == kOpReleaseMem ? 2u : 3u;
                if ((out[i + dc] & (3u << 24)) != 0) {
                    out[i + dc] &= ~(3u << 24);
                    stats.int_sel_rewrites++;
                }
            }
            std::uint32_t base = 0;
            if (is_plain_set(opcode, base) && len >= 3) {
                const std::uint32_t offset = src[i + 1] & 0xffff;
                for (std::uint32_t k = 0; k + 2 < len; ++k) {
                    const std::uint32_t mm = base + offset + k;
                    if (policy.reg(mm) != Verdict::Rewrite) continue;
                    std::uint32_t &val = out[i + 2 + k];
                    switch (mm) {
                    case kMmComputeStaticThreadMgmtSe0:
                    case kMmComputeStaticThreadMgmtSe1:
                    case kMmComputeStaticThreadMgmtSe2:
                    case kMmComputeStaticThreadMgmtSe3:
                        val &= opt.cu_mask;
                        stats.cu_mask_rewrites++;
                        break;
                    case kMmSpiShaderPgmRsrc3Ps:
                    case kMmSpiShaderPgmRsrc3Vs:
                    case kMmSpiShaderPgmRsrc3Gs:
                    case kMmSpiShaderPgmRsrc3Hs:
                        val = (val & ~0xffffu) | (val & opt.cu_mask & 0xffffu); // CU_EN bits 15:0
                        stats.cu_mask_rewrites++;
                        break;
                    default: break; // a rewrite the table names but the filter does not know
                    }
                }
            }
            break;
        }
        }
        i += len;
    }
    return i;
}

} // namespace bc5::policy
