// SPDX-License-Identifier: GPL-2.0-only
#include "bc5/policy.hpp"

#include "policy_tsv.hpp" // generated by CMake from backend/policy/pm4-policy.tsv

#include <algorithm>
#include <charconv>
#include <stdexcept>
#include <string>
#include <utility>

namespace bc5::policy {

namespace {

bool parse_hex(std::string_view s, std::uint32_t &out) {
    while (!s.empty() && (s.front() == ' ' || s.front() == '\t')) s.remove_prefix(1);
    while (!s.empty() && (s.back() == ' ' || s.back() == '\t' || s.back() == '\r')) s.remove_suffix(1);
    if (s.starts_with("0x") || s.starts_with("0X")) s.remove_prefix(2);
    if (s.empty()) return false;
    auto r = std::from_chars(s.data(), s.data() + s.size(), out, 16);
    return r.ec == std::errc{} && r.ptr == s.data() + s.size();
}

bool parse_verdict(std::string_view s, Verdict &v) {
    while (!s.empty() && s.back() == '\r') s.remove_suffix(1);
    if (s == "pass") v = Verdict::Pass;
    else if (s == "rewrite") v = Verdict::Rewrite;
    else if (s == "drop") v = Verdict::Drop;
    else return false;
    return true;
}

std::vector<std::string_view> split_tabs(std::string_view line) {
    std::vector<std::string_view> cols;
    while (true) {
        auto tab = line.find('\t');
        if (tab == std::string_view::npos) {
            cols.push_back(line);
            break;
        }
        cols.push_back(line.substr(0, tab));
        line.remove_prefix(tab + 1);
    }
    return cols;
}

// SET_CONFIG_REG, SET_CONTEXT_REG, SET_SH_REG, SET_UCONFIG_REG, SET_SH_REG_INDEX: dword1 = offset.
bool is_plain_set(std::uint8_t op, std::uint32_t &base) {
    switch (op) {
    case 0x68: base = 0x2000; return true;
    case 0x69: base = 0xa000; return true;
    case 0x76:
    case 0x9b: base = 0x2c00; return true;
    case 0x79: base = 0xc000; return true;
    default: return false;
    }
}

constexpr std::uint32_t kMmComputeStaticThreadMgmtSe0 = 0x2e16;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe1 = 0x2e17;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe2 = 0x2e19;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe3 = 0x2e1a;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Ps = 0x2c07;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Vs = 0x2c47;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Gs = 0x2c87;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Hs = 0x2d07;

} // namespace

// Memory operands of a packet: (address, bytes) pairs the CP reads or writes. Layouts after
// RPCSX rpcsx/gpu/Pipe.cpp @ e8ae148 and Mesa src/amd/common/sid.h. Unknown/none: empty.
std::vector<std::pair<std::uint64_t, std::uint64_t>> memory_operands(const std::uint32_t *p,
                                                                     std::uint32_t len) {
    std::vector<std::pair<std::uint64_t, std::uint64_t>> out;
    if ((p[0] >> 30) != 3 || len < 2) return out;
    const auto op = static_cast<std::uint8_t>((p[0] >> 8) & 0xff);
    auto addr = [&](std::uint32_t lo_idx, std::uint32_t hi_idx, std::uint32_t hi_mask = 0xffffu) {
        return (static_cast<std::uint64_t>(p[lo_idx]) & ~3ull) |
               (static_cast<std::uint64_t>(p[hi_idx] & hi_mask) << 32);
    };
    switch (op) {
    case 0x3f: // INDIRECT_BUFFER
    case 0x33: // INDIRECT_BUFFER_CNST
        if (len >= 4) out.emplace_back(addr(1, 2, 0xffu), (p[3] & 0xfffffu) * 4ull);
        break;
    case 0x5e: // LOAD_UCONFIG_REG
    case 0x5f: // LOAD_SH_REG
    case 0x61: // LOAD_CONTEXT_REG
        if (len >= 3) out.emplace_back(addr(1, 2), 4096); // table of (offset, count) pairs
        break;
    case 0x63: // LOAD_SH_REG_INDEX
    case 0x64: // LOAD_UCONFIG_REG_INDEX
    case 0x9f: // LOAD_CONTEXT_REG_INDEX
        if (len >= 5) out.emplace_back(addr(1, 2), (p[4] & 0x3fffu) * 4ull + 4);
        break;
    case 0x22: // COND_EXEC
        if (len >= 3) out.emplace_back(addr(1, 2), 4);
        break;
    case 0x37: { // WRITE_DATA: dst_sel bits 11:8, 1/2/5 = memory
        const std::uint32_t dst_sel = (p[1] >> 8) & 0xf;
        if (len >= 4 && (dst_sel == 1 || dst_sel == 2 || dst_sel == 5))
            out.emplace_back(addr(2, 3), (len - 4) * 4ull);
        break;
    }
    case 0x49: // RELEASE_MEM (gfx10): addr lo/hi at 3/4; DATA_SEL 0 (bits 31:29 of dword 2)
               // writes nothing — an event/cache-flush only packet, address 0 is normal
        if (len >= 6 && ((p[2] >> 29) & 7) != 0) out.emplace_back(addr(3, 4), 8);
        break;
    case 0x47: // EVENT_WRITE_EOP: addr lo at 2, hi in dword 3 bits 15:0; DATA_SEL 0 = no write
        if (len >= 4 && ((p[3] >> 29) & 7) != 0) out.emplace_back(addr(2, 3), 8);
        break;
    case 0x3c: // WAIT_REG_MEM: mem_space bit 4
    case 0x93: // WAIT_REG_MEM64
        if (len >= 4 && ((p[1] >> 4) & 1)) out.emplace_back(addr(2, 3), 8);
        break;
    case 0x1e: // ATOMIC_MEM
        if (len >= 4) out.emplace_back(addr(2, 3), 8);
        break;
    case 0x40: { // COPY_DATA: src_sel bits 3:0, dst_sel bits 11:8
        const std::uint32_t src_sel = p[1] & 0xf, dst_sel = (p[1] >> 8) & 0xf;
        if (len >= 6) {
            if (src_sel == 1 || src_sel == 2) out.emplace_back(addr(2, 3), 8);
            if (dst_sel == 1 || dst_sel == 2 || dst_sel == 5) out.emplace_back(addr(4, 5), 8);
        }
        break;
    }
    case 0x50: { // DMA_DATA: src lo/hi 2/3, dst lo/hi 4/5, count in dword 6 (bits 25:0)
        // SRC_SEL (bits 30:29): 0 SRC_ADDR, 1 GDS, 2 DATA, 3 SRC_ADDR_TC_L2; DST_SEL (bits 21:20):
        // 0 DST_ADDR, 1 GDS, 2 NOWHERE, 3 DST_ADDR_TC_L2 (Mesa sid.h V_411_*). Only 0 and 3 are
        // memory: a GDS selector's address field is a GDS byte offset, not an address (treating
        // it as one dropped every GDS fill and read-back of the game, experiment 0016 run 59).
        if (len >= 7) {
            const std::uint64_t bytes = p[6] & 0x3ffffffu;
            const std::uint32_t src_sel = (p[1] >> 29) & 3, dst_sel = (p[1] >> 20) & 3;
            if (src_sel == 0 || src_sel == 3) out.emplace_back(addr(2, 3, 0xffffffffu), bytes);
            if (dst_sel == 0 || dst_sel == 3) out.emplace_back(addr(4, 5, 0xffffffffu), bytes);
        }
        break;
    }
    case 0x11: // SET_BASE: base_index at 1, addr lo/hi at 2/3
        if (len >= 4 && (p[2] != 0 || p[3] != 0)) out.emplace_back(addr(2, 3), 4);
        break;
    case 0x26: // INDEX_BASE
        if (len >= 3 && (p[1] != 0 || p[2] != 0)) out.emplace_back(addr(1, 2), 4);
        break;
    default: break;
    }
    return out;
}

bool is_gds_access(const std::uint32_t *p, std::uint32_t len) {
    const auto op = static_cast<std::uint8_t>((p[0] >> 8) & 0xff);
    if (op == 0x50 && len >= 7) { // DMA_DATA: SRC_SEL bits 30:29, DST_SEL bits 21:20; 1 = GDS
        return ((p[1] >> 29) & 3) == 1 || ((p[1] >> 20) & 3) == 1;
    }
    if (op == kOpWriteData && len >= 2) { // WRITE_DATA: DST_SEL bits 11:8; 3 = GDS (2 is TC_L2 memory)
        return ((p[1] >> 8) & 0xf) == 3;
    }
    return false;
}

bool mask_cu_register(std::uint32_t mm, std::uint32_t &value, std::uint32_t cu_mask) {
    switch (mm) {
    case kMmComputeStaticThreadMgmtSe0:
    case kMmComputeStaticThreadMgmtSe1:
    case kMmComputeStaticThreadMgmtSe2:
    case kMmComputeStaticThreadMgmtSe3:
        value &= cu_mask;
        return true;
    case kMmSpiShaderPgmRsrc3Ps:
    case kMmSpiShaderPgmRsrc3Vs:
    case kMmSpiShaderPgmRsrc3Gs:
        value = (value & ~0xffffu) | (value & cu_mask & 0xffffu); // CU_EN bits 15:0
        return true;
    case kMmSpiShaderPgmRsrc3Hs:
        value = (value & 0xffffu) | (value & ((cu_mask & 0xffffu) << 16)); // CU_EN bits 31:16
        return true;
    default: return false;
    }
}

bool is_draw_or_dispatch(std::uint8_t opcode) {
    switch (opcode) {
    case 0x15: // DISPATCH_DIRECT
    case 0x16: // DISPATCH_INDIRECT
    case 0x25: // DRAW_INDEX_INDIRECT
    case 0x27: // DRAW_INDEX_2
    case 0x2d: // DRAW_INDEX_AUTO
    case 0x35: // DRAW_INDEX_OFFSET_2
    case 0x38: // DRAW_INDEX_MULTI_AUTO
    case 0x24: // DRAW_INDIRECT
        return true;
    default:
        return false;
    }
}

const char *verdict_name(Verdict v) {
    switch (v) {
    case Verdict::Pass: return "pass";
    case Verdict::Rewrite: return "rewrite";
    case Verdict::Split: return "split";
    case Verdict::Drop: return "drop";
    }
    return "?";
}

Policy Policy::parse(std::string_view tsv) {
    Policy p;
    for (auto &v : p.ops_) v = Verdict::Drop;
    std::size_t line_no = 0;
    while (!tsv.empty()) {
        ++line_no;
        auto nl = tsv.find('\n');
        std::string_view line = tsv.substr(0, nl);
        tsv = nl == std::string_view::npos ? std::string_view{} : tsv.substr(nl + 1);
        if (!line.empty() && line.back() == '\r') line.remove_suffix(1);
        if (line.empty() || line.front() == '#') continue;
        auto cols = split_tabs(line);
        auto bad = [&](const char *what) {
            throw std::invalid_argument("pm4-policy.tsv line " + std::to_string(line_no) + ": " +
                                        what);
        };
        Verdict v{};
        if (cols[0] == "default-op" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.default_op_ = v;
        } else if (cols[0] == "default-reg" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.default_reg_ = v;
        } else if (cols[0] == "type0" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.type0_ = v;
        } else if (cols[0] == "op" && cols.size() >= 3) {
            std::uint32_t op = 0;
            if (!parse_hex(cols[1], op) || op > 0xff) bad("opcode");
            if (!parse_verdict(cols[2], v)) bad("verdict");
            p.ops_[op] = v;
            p.op_set_[op] = true;
        } else if (cols[0] == "reg" && cols.size() >= 3) {
            std::uint32_t a = 0, b = 0;
            auto dash = cols[1].find('-');
            if (dash == std::string_view::npos) {
                if (!parse_hex(cols[1], a)) bad("register");
                b = a;
            } else if (!parse_hex(cols[1].substr(0, dash), a) ||
                       !parse_hex(cols[1].substr(dash + 1), b)) {
                bad("register");
            }
            if (!parse_verdict(cols[2], v)) bad("verdict");
            p.regs_.push_back({a, b, v});
        } else {
            bad("unknown kind");
        }
    }
    return p;
}

const Policy &Policy::builtin() {
    static const Policy p = Policy::parse(kPolicyTsv);
    return p;
}

Verdict Policy::op(std::uint8_t opcode) const {
    return op_set_[opcode] ? ops_[opcode] : default_op_;
}

Verdict Policy::reg(std::uint32_t mm) const {
    for (const auto &r : regs_) {
        if (mm >= r.first && mm <= r.last) return r.verdict;
    }
    return default_reg_;
}

Verdict Policy::packet(const std::uint32_t *p, std::uint32_t len) const {
    const std::uint32_t header = p[0];
    const std::uint32_t type = header >> 30;
    if (type == 2) return Verdict::Pass;
    if (type == 0) return type0_;
    if (type == 1) return Verdict::Drop;
    const auto opcode = static_cast<std::uint8_t>((header >> 8) & 0xff);
    const Verdict ov = op(opcode);
    std::uint32_t base = 0;
    if (ov != Verdict::Pass || !is_plain_set(opcode, base) || len < 2) return ov;
    const std::uint32_t offset = p[1] & 0xffff;
    bool seen = false;
    Verdict first{};
    for (std::uint32_t i = 0; i + 2 < len; ++i) {
        const Verdict rv = reg(base + offset + i);
        if (!seen) {
            first = rv;
            seen = true;
        } else if (rv != first) {
            return Verdict::Split;
        }
    }
    return seen ? first : Verdict::Pass;
}

std::size_t filter(const Policy &policy, std::span<const std::uint32_t> src,
                   std::span<std::uint32_t> out, const FilterOptions &opt, FilterStats &stats) {
    const std::size_t n = src.size();
    std::size_t i = 0;
    // Labels written earlier in this IB by packets that pass (WRITE_DATA to memory, RELEASE_MEM,
    // EVENT_WRITE_EOP, ATOMIC_MEM): a wait on anything else cannot be satisfied by this
    // submission and would stall the ring until the kernel's GPU timeout (a machine reset on
    // the BC-250), so it is dropped and left to the host (ADR 0005, experiment 0016 step c3).
    std::vector<std::uint64_t> written;
    auto label_of = [](const std::uint32_t *p, std::uint32_t len, std::uint8_t op) -> std::uint64_t {
        auto a = [&](std::uint32_t lo, std::uint32_t hi) {
            return (static_cast<std::uint64_t>(p[lo]) & ~3ull) |
                   (static_cast<std::uint64_t>(p[hi] & 0xffffu) << 32);
        };
        const std::uint32_t dst_sel = len >= 2 ? (p[1] >> 8) & 0xf : 0;
        switch (op) {
        case kOpWriteData:
            return (len >= 4 && (dst_sel == 1 || dst_sel == 2 || dst_sel == 5)) ? a(2, 3) : 0;
        case kOpReleaseMem: return len >= 6 ? a(3, 4) : 0;
        case kOpEventWriteEop: return len >= 4 ? a(2, 3) : 0;
        case 0x1e: return len >= 4 ? a(2, 3) : 0; // ATOMIC_MEM
        default: return 0;
        }
    };
    while (i < n) {
        const std::uint32_t header = src[i];
        const std::uint32_t type = header >> 30;
        std::uint32_t len = 1;
        if (type == 0 || type == 3) {
            const std::uint32_t count = (header >> 16) & 0x3fff;
            len = count == 0x3fff ? 1 : count + 2;
        } else if (type == 1) {
            len = 1;
        }
        stats.packets++;
        stats.dwords += len;
        if (i + len > n) {
            // A packet running past the end: NOP the remainder, the CP must not read past it.
            stats.truncated++;
            for (std::size_t k = i; k < n; ++k) out[k] = kNop;
            stats.dwords_dropped += n - i;
            i = n;
            break;
        }
        Verdict v = policy.packet(&src[i], len);
        const auto opcode3 = static_cast<std::uint8_t>((header >> 8) & 0xff);
        bool sample_here = false;
        if (type == 3 && v != Verdict::Drop) {
            if (opt.drop_draws && is_draw_or_dispatch(opcode3)) {
                v = Verdict::Drop;
            } else if (!opt.drop_offsets.empty() &&
                       std::find(opt.drop_offsets.begin(), opt.drop_offsets.end(),
                                 static_cast<std::uint32_t>(i)) != opt.drop_offsets.end()) {
                v = Verdict::Drop;
                stats.offset_drops++;
            } else if (opt.self_waits_only && (opcode3 == 0x3c || opcode3 == 0x93) && len >= 4) {
                // WAIT_REG_MEM[64]: mem_space is bit 4 of the control dword; register polls and
                // waits on labels nobody in this IB writes are dropped.
                const bool mem_space = ((src[i + 1] >> 4) & 1) != 0;
                const std::uint64_t target = (static_cast<std::uint64_t>(src[i + 2]) & ~3ull) |
                                             (static_cast<std::uint64_t>(src[i + 3] & 0xffffu) << 32);
                if (!mem_space || std::find(written.begin(), written.end(), target) == written.end()) {
                    v = Verdict::Drop;
                    stats.unsatisfiable_wait_drops++;
                }
            } else if (opt.gds_shadow_va != 0 && is_gds_access(&src[i], len)) {
                v = Verdict::Rewrite; // redirected below, once the packet is in the output
            } else if (opt.drop_gds && is_gds_access(&src[i], len)) {
                // GDS (global data share) through the CP: DMA_DATA with SRC_SEL/DST_SEL 1 and
                // WRITE_DATA with DST_SEL 3 (Mesa sid.h V_411_GDS, V_370_GDS). The console's
                // compute IBs fill and read GDS counters this way; our VMID has no GDS
                // allocation unless a GDS BO is on the BO list (Device::OpenOptions::gds_kib).
                v = Verdict::Drop;
                stats.gds_drops++;
            } else if (opcode3 == kOpWriteData && len >= 2 && ((src[i + 1] >> 8) & 0xf) == 0) {
                // WRITE_DATA with DST_SEL 0 writes a register (the console's driver uses it for
                // SQ_THREAD_TRACE_USERDATA_3 markers, mm 0xc343): the register policy applies to
                // SET_* only, so register destinations are dropped outright (ADR 0005).
                v = Verdict::Drop;
                stats.reg_write_drops++;
                sample_here = opt.stat_sample_va != 0 && len >= 4 &&
                              stats.stat_sample_offsets.size() < opt.stat_sample_max;
            } else if (!opt.extra_drop.empty() &&
                       std::find(opt.extra_drop.begin(), opt.extra_drop.end(), opcode3) !=
                           opt.extra_drop.end()) {
                v = Verdict::Drop;
                stats.extra_drops++;
            } else if (opt.mec_indirect_base != 0 && opcode3 == 0x16 && len == 4) {
                // DISPATCH_INDIRECT in the compute-queue form (FilterOptions::mec_indirect_base).
                const std::uint64_t hi = static_cast<std::uint64_t>(src[i + 2] & 0xffffu) << 32;
                if (hi != opt.mec_indirect_base) {
                    v = Verdict::Drop;
                    stats.mec_indirect_drops++;
                } else {
                    v = Verdict::Rewrite; // rewritten below
                }
            } else if (opt.mapped) {
                for (const auto &[a, bytes] : memory_operands(&src[i], len)) {
                    if (!opt.mapped(a, bytes == 0 ? 4 : bytes)) {
                        v = Verdict::Drop;
                        stats.unmapped_drops++;
                        break;
                    }
                }
            }
        }
        switch (v) {
        case Verdict::Drop:
            for (std::uint32_t k = 0; k < len; ++k) out[i + k] = kNop;
            if (sample_here) {
                // EVENT_WRITE, SAMPLE_PIPELINESTAT (event 30, EVENT_INDEX 2) + address, as RADV
                // emits it for pipeline-statistics queries (Mesa radv_query.c).
                const std::uint64_t a =
                    opt.stat_sample_va + stats.stat_sample_offsets.size() * kStatSampleStride;
                out[i] = 0xC0024600u;
                out[i + 1] = 30u | (2u << 8);
                out[i + 2] = static_cast<std::uint32_t>(a);
                out[i + 3] = static_cast<std::uint32_t>(a >> 32);
                stats.stat_sample_offsets.push_back(static_cast<std::uint32_t>(i));
            }
            stats.dropped++;
            stats.dwords_dropped += len;
            break;
        case Verdict::Pass:
        case Verdict::Rewrite:
        case Verdict::Split: {
            for (std::uint32_t k = 0; k < len; ++k) out[i + k] = src[i + k];
            if (v == Verdict::Pass) stats.passed++;
            else if (v == Verdict::Rewrite) stats.rewritten++;
            else stats.split++;
            if (type != 3) break;
            if (const std::uint64_t label = label_of(&src[i], len, opcode3); label != 0)
                written.push_back(label);
            const auto opcode = static_cast<std::uint8_t>((header >> 8) & 0xff);
            if (opcode == kOpContextControl && opt.safe_context_control && len >= 3 &&
                (out[i + 1] != 0x80000000u || out[i + 2] != 0x80000000u)) {
                out[i + 1] = 0x80000000u;
                out[i + 2] = 0x80000000u;
                stats.context_control_rewrites++;
            }
            if (opt.gcr_clear != 0 && opcode == 0x58 && len >= 8 && (out[i + 7] & opt.gcr_clear) != 0) {
                out[i + 7] &= ~opt.gcr_clear; // ACQUIRE_MEM GCR_CNTL (experiment 0044)
                stats.gcr_rewrites++;
            }
            if (!opt.drop_gds && opt.gds_shadow_va == 0 && opcode == 0x50 && is_gds_access(&src[i], len) &&
                (out[i + 1] & 0x80000000u) != 0) {
                // A GDS DMA with CP_SYNC (bit 31) on the GFX ring stalled the CP (run 49, #143);
                // the same DMA without it is the shape the compute queues use all the time. The
                // gfx queue's GDS fills are the counter resets (run 56: never reset, the counters
                // grew by one per frame across processes), so they must reach GDS: strip CP_SYNC.
                out[i + 1] &= ~0x80000000u;
                stats.gds_rewrites++;
            }
            if (opt.gds_shadow_va != 0 && is_gds_access(&src[i], len)) {
                // DMA_DATA: SRC_SEL bits 30:29 (0 SRC_ADDR, 1 GDS, 2 DATA, 3 SRC_ADDR_TC_L2),
                // DST_SEL bits 21:20 (0 DST_ADDR, 1 GDS, 2 NOWHERE, 3 DST_ADDR_TC_L2); the GDS side's
                // address field holds the byte offset into GDS (Mesa sid.h, PAL DMA_DATA).
                if (opcode == 0x50) {
                    if (((out[i + 1] >> 29) & 3) == 1) {
                        const std::uint64_t a = opt.gds_shadow_va + (out[i + 2] & 0xffffu);
                        out[i + 1] = (out[i + 1] & ~(3u << 29)) | (3u << 29);
                        out[i + 2] = static_cast<std::uint32_t>(a);
                        out[i + 3] = static_cast<std::uint32_t>(a >> 32);
                    }
                    if (((out[i + 1] >> 20) & 3) == 1) {
                        const std::uint64_t a = opt.gds_shadow_va + (out[i + 4] & 0xffffu);
                        out[i + 1] = (out[i + 1] & ~(3u << 20)) | (3u << 20);
                        out[i + 4] = static_cast<std::uint32_t>(a);
                        out[i + 5] = static_cast<std::uint32_t>(a >> 32);
                    }
                } else if (opcode == kOpWriteData && len >= 4) { // DST_SEL 3 (GDS) -> 5 (memory)
                    const std::uint64_t a = opt.gds_shadow_va + (out[i + 2] & 0xffffu);
                    out[i + 1] = (out[i + 1] & ~(0xfu << 8)) | (5u << 8);
                    out[i + 2] = static_cast<std::uint32_t>(a);
                    out[i + 3] = static_cast<std::uint32_t>(a >> 32);
                }
                stats.gds_rewrites++;
            }
            if (opt.mec_indirect_base != 0 && opcode == 0x16 && len == 4) {
                // offset (the low address dword) and initiator for the GFX ring, one NOP after;
                // the header keeps its predicate and shader-type bits, count 1.
                out[i] = (header & ~(0x3fffu << 16)) | (1u << 16);
                out[i + 1] = src[i + 1] & ~3u;
                out[i + 2] = src[i + 3];
                out[i + 3] = kNop;
                stats.mec_indirect_rewrites++;
            }
            if (opcode == 0x12 && len >= 2 && out[i + 1] != 0) { // CLEAR_STATE: only cmd 0 is AMD's
                out[i + 1] = 0;
                stats.clear_state_rewrites++;
            }
            if (opt.ordered_append_enable && ((opcode == 0x15 && len >= 5) || (opcode == 0x16 && len >= 3))) {
                // DISPATCH_DIRECT: dim x, y, z, initiator; DISPATCH_INDIRECT: data offset, initiator.
                std::uint32_t &init = out[i + (opcode == 0x15 ? 4 : 2)];
                if ((init & 0x8u) == 0) {
                    init |= 0x8u;
                    stats.dispatch_rewrites++;
                }
            }
            if (opcode == kOpReleaseMem && opt.cs_done_to_bottom_of_pipe && len >= 3 &&
                ((out[i + 1] >> 8) & 0xf) == 6 && ((out[i + 2] >> 29) & 7) == 0) {
                // RELEASE_MEM with EVENT_INDEX 6 (CS_DONE / PS_DONE) and no data: the console's
                // compute IBs end every dispatch batch with one (address 0, cache flush only);
                // on the BC-250's GFX ring it never completes (experiment 0016, run 40, found
                // by the piecewise mode). Same packet with BOTTOM_OF_PIPE_TS / index 5 — the
                // shape that passes everywhere else — keeps the flush and the ordering.
                out[i + 1] = (out[i + 1] & ~0xf3fu) | 0x28u | (5u << 8);
                stats.cs_done_rewrites++;
            }
            if ((opcode == kOpReleaseMem || opcode == kOpEventWriteEop) && opt.clear_int_sel &&
                len >= 4) {
                // RELEASE_MEM: data_cntl is dword 2; EVENT_WRITE_EOP: dword 3. INT_SEL = bits 25:24.
                const std::uint32_t dc = opcode == kOpReleaseMem ? 2u : 3u;
                if ((out[i + dc] & (3u << 24)) != 0) {
                    out[i + dc] &= ~(3u << 24);
                    stats.int_sel_rewrites++;
                }
            }
            std::uint32_t base = 0;
            if (is_plain_set(opcode, base) && len >= 3) {
                const std::uint32_t offset = src[i + 1] & 0xffff;
                for (std::uint32_t k = 0; k + 2 < len; ++k) {
                    const std::uint32_t mm = base + offset + k;
                    if (policy.reg(mm) != Verdict::Rewrite) continue;
                    std::uint32_t &val = out[i + 2 + k];
                    // a rewrite the table names but the filter does not know is left as it is
                    if (mask_cu_register(mm, val, opt.cu_mask)) stats.cu_mask_rewrites++;
                }
            }
            break;
        }
        }
        i += len;
    }
    return i;
}

} // namespace bc5::policy
