// SPDX-License-Identifier: GPL-2.0-only
#include "bc5/policy.hpp"

#include "policy_tsv.hpp" // generated by CMake from backend/policy/pm4-policy.tsv

#include <algorithm>
#include <charconv>
#include <stdexcept>
#include <string>
#include <utility>

namespace bc5::policy {

namespace {

bool parse_hex(std::string_view s, std::uint32_t &out) {
    while (!s.empty() && (s.front() == ' ' || s.front() == '\t')) s.remove_prefix(1);
    while (!s.empty() && (s.back() == ' ' || s.back() == '\t' || s.back() == '\r')) s.remove_suffix(1);
    if (s.starts_with("0x") || s.starts_with("0X")) s.remove_prefix(2);
    if (s.empty()) return false;
    auto r = std::from_chars(s.data(), s.data() + s.size(), out, 16);
    return r.ec == std::errc{} && r.ptr == s.data() + s.size();
}

bool parse_verdict(std::string_view s, Verdict &v) {
    while (!s.empty() && s.back() == '\r') s.remove_suffix(1);
    if (s == "pass") v = Verdict::Pass;
    else if (s == "rewrite") v = Verdict::Rewrite;
    else if (s == "drop") v = Verdict::Drop;
    else return false;
    return true;
}

std::vector<std::string_view> split_tabs(std::string_view line) {
    std::vector<std::string_view> cols;
    while (true) {
        auto tab = line.find('\t');
        if (tab == std::string_view::npos) {
            cols.push_back(line);
            break;
        }
        cols.push_back(line.substr(0, tab));
        line.remove_prefix(tab + 1);
    }
    return cols;
}

// SET_CONFIG_REG, SET_CONTEXT_REG, SET_SH_REG, SET_UCONFIG_REG, SET_SH_REG_INDEX: dword1 = offset.
bool is_plain_set(std::uint8_t op, std::uint32_t &base) {
    switch (op) {
    case 0x68: base = 0x2000; return true;
    case 0x69: base = 0xa000; return true;
    case 0x76:
    case 0x9b: base = 0x2c00; return true;
    case 0x79: base = 0xc000; return true;
    default: return false;
    }
}

constexpr std::uint32_t kMmComputeStaticThreadMgmtSe0 = 0x2e16;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe1 = 0x2e17;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe2 = 0x2e19;
constexpr std::uint32_t kMmComputeStaticThreadMgmtSe3 = 0x2e1a;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Ps = 0x2c07;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Vs = 0x2c47;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Gs = 0x2c87;
constexpr std::uint32_t kMmSpiShaderPgmRsrc3Hs = 0x2d07;

} // namespace

// Memory operands of a packet: (address, bytes) pairs the CP reads or writes. Layouts after
// RPCSX rpcsx/gpu/Pipe.cpp @ e8ae148 and Mesa src/amd/common/sid.h. Unknown/none: empty.
std::vector<std::pair<std::uint64_t, std::uint64_t>> memory_operands(const std::uint32_t *p,
                                                                     std::uint32_t len) {
    std::vector<std::pair<std::uint64_t, std::uint64_t>> out;
    if ((p[0] >> 30) != 3 || len < 2) return out;
    const auto op = static_cast<std::uint8_t>((p[0] >> 8) & 0xff);
    auto addr = [&](std::uint32_t lo_idx, std::uint32_t hi_idx, std::uint32_t hi_mask = 0xffffu) {
        return (static_cast<std::uint64_t>(p[lo_idx]) & ~3ull) |
               (static_cast<std::uint64_t>(p[hi_idx] & hi_mask) << 32);
    };
    switch (op) {
    case 0x3f: // INDIRECT_BUFFER
    case 0x33: // INDIRECT_BUFFER_CNST
        if (len >= 4) out.emplace_back(addr(1, 2, 0xffu), (p[3] & 0xfffffu) * 4ull);
        break;
    case 0x5e: // LOAD_UCONFIG_REG
    case 0x5f: // LOAD_SH_REG
    case 0x61: // LOAD_CONTEXT_REG
        if (len >= 3) out.emplace_back(addr(1, 2), 4096); // table of (offset, count) pairs
        break;
    case 0x63: // LOAD_SH_REG_INDEX
    case 0x64: // LOAD_UCONFIG_REG_INDEX
    case 0x9f: // LOAD_CONTEXT_REG_INDEX
        if (len >= 5) out.emplace_back(addr(1, 2), (p[4] & 0x3fffu) * 4ull + 4);
        break;
    case 0x22: // COND_EXEC
        if (len >= 3) out.emplace_back(addr(1, 2), 4);
        break;
    case 0x37: { // WRITE_DATA: dst_sel bits 11:8, 1/2/5 = memory
        const std::uint32_t dst_sel = (p[1] >> 8) & 0xf;
        if (len >= 4 && (dst_sel == 1 || dst_sel == 2 || dst_sel == 5))
            out.emplace_back(addr(2, 3), (len - 4) * 4ull);
        break;
    }
    case 0x49: // RELEASE_MEM (gfx10): addr lo/hi at 3/4
        if (len >= 6) out.emplace_back(addr(3, 4), 8);
        break;
    case 0x47: // EVENT_WRITE_EOP: addr lo at 2, hi in dword 3 bits 15:0
        if (len >= 4) out.emplace_back(addr(2, 3), 8);
        break;
    case 0x3c: // WAIT_REG_MEM: mem_space bit 4
    case 0x93: // WAIT_REG_MEM64
        if (len >= 4 && ((p[1] >> 4) & 1)) out.emplace_back(addr(2, 3), 8);
        break;
    case 0x1e: // ATOMIC_MEM
        if (len >= 4) out.emplace_back(addr(2, 3), 8);
        break;
    case 0x40: { // COPY_DATA: src_sel bits 3:0, dst_sel bits 11:8
        const std::uint32_t src_sel = p[1] & 0xf, dst_sel = (p[1] >> 8) & 0xf;
        if (len >= 6) {
            if (src_sel == 1 || src_sel == 2) out.emplace_back(addr(2, 3), 8);
            if (dst_sel == 1 || dst_sel == 2 || dst_sel == 5) out.emplace_back(addr(4, 5), 8);
        }
        break;
    }
    case 0x50: { // DMA_DATA: src lo/hi 2/3, dst lo/hi 4/5, count in dword 6 (bits 25:0)
        if (len >= 7) {
            const std::uint64_t bytes = p[6] & 0x3ffffffu;
            const std::uint32_t src_sel = (p[1] >> 29) & 3, dst_sel = (p[1] >> 20) & 3;
            if (src_sel == 0 || src_sel == 1) out.emplace_back(addr(2, 3, 0xffffffffu), bytes);
            if (dst_sel == 0 || dst_sel == 1) out.emplace_back(addr(4, 5, 0xffffffffu), bytes);
        }
        break;
    }
    case 0x11: // SET_BASE: base_index at 1, addr lo/hi at 2/3
        if (len >= 4 && (p[2] != 0 || p[3] != 0)) out.emplace_back(addr(2, 3), 4);
        break;
    case 0x26: // INDEX_BASE
        if (len >= 3 && (p[1] != 0 || p[2] != 0)) out.emplace_back(addr(1, 2), 4);
        break;
    default: break;
    }
    return out;
}

bool is_draw_or_dispatch(std::uint8_t opcode) {
    switch (opcode) {
    case 0x15: // DISPATCH_DIRECT
    case 0x16: // DISPATCH_INDIRECT
    case 0x25: // DRAW_INDEX_INDIRECT
    case 0x27: // DRAW_INDEX_2
    case 0x2d: // DRAW_INDEX_AUTO
    case 0x35: // DRAW_INDEX_OFFSET_2
    case 0x38: // DRAW_INDEX_MULTI_AUTO
    case 0x24: // DRAW_INDIRECT
        return true;
    default:
        return false;
    }
}

const char *verdict_name(Verdict v) {
    switch (v) {
    case Verdict::Pass: return "pass";
    case Verdict::Rewrite: return "rewrite";
    case Verdict::Split: return "split";
    case Verdict::Drop: return "drop";
    }
    return "?";
}

Policy Policy::parse(std::string_view tsv) {
    Policy p;
    for (auto &v : p.ops_) v = Verdict::Drop;
    std::size_t line_no = 0;
    while (!tsv.empty()) {
        ++line_no;
        auto nl = tsv.find('\n');
        std::string_view line = tsv.substr(0, nl);
        tsv = nl == std::string_view::npos ? std::string_view{} : tsv.substr(nl + 1);
        if (!line.empty() && line.back() == '\r') line.remove_suffix(1);
        if (line.empty() || line.front() == '#') continue;
        auto cols = split_tabs(line);
        auto bad = [&](const char *what) {
            throw std::invalid_argument("pm4-policy.tsv line " + std::to_string(line_no) + ": " +
                                        what);
        };
        Verdict v{};
        if (cols[0] == "default-op" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.default_op_ = v;
        } else if (cols[0] == "default-reg" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.default_reg_ = v;
        } else if (cols[0] == "type0" && cols.size() >= 2) {
            if (!parse_verdict(cols[1], v)) bad("verdict");
            p.type0_ = v;
        } else if (cols[0] == "op" && cols.size() >= 3) {
            std::uint32_t op = 0;
            if (!parse_hex(cols[1], op) || op > 0xff) bad("opcode");
            if (!parse_verdict(cols[2], v)) bad("verdict");
            p.ops_[op] = v;
            p.op_set_[op] = true;
        } else if (cols[0] == "reg" && cols.size() >= 3) {
            std::uint32_t a = 0, b = 0;
            auto dash = cols[1].find('-');
            if (dash == std::string_view::npos) {
                if (!parse_hex(cols[1], a)) bad("register");
                b = a;
            } else if (!parse_hex(cols[1].substr(0, dash), a) ||
                       !parse_hex(cols[1].substr(dash + 1), b)) {
                bad("register");
            }
            if (!parse_verdict(cols[2], v)) bad("verdict");
            p.regs_.push_back({a, b, v});
        } else {
            bad("unknown kind");
        }
    }
    return p;
}

const Policy &Policy::builtin() {
    static const Policy p = Policy::parse(kPolicyTsv);
    return p;
}

Verdict Policy::op(std::uint8_t opcode) const {
    return op_set_[opcode] ? ops_[opcode] : default_op_;
}

Verdict Policy::reg(std::uint32_t mm) const {
    for (const auto &r : regs_) {
        if (mm >= r.first && mm <= r.last) return r.verdict;
    }
    return default_reg_;
}

Verdict Policy::packet(const std::uint32_t *p, std::uint32_t len) const {
    const std::uint32_t header = p[0];
    const std::uint32_t type = header >> 30;
    if (type == 2) return Verdict::Pass;
    if (type == 0) return type0_;
    if (type == 1) return Verdict::Drop;
    const auto opcode = static_cast<std::uint8_t>((header >> 8) & 0xff);
    const Verdict ov = op(opcode);
    std::uint32_t base = 0;
    if (ov != Verdict::Pass || !is_plain_set(opcode, base) || len < 2) return ov;
    const std::uint32_t offset = p[1] & 0xffff;
    bool seen = false;
    Verdict first{};
    for (std::uint32_t i = 0; i + 2 < len; ++i) {
        const Verdict rv = reg(base + offset + i);
        if (!seen) {
            first = rv;
            seen = true;
        } else if (rv != first) {
            return Verdict::Split;
        }
    }
    return seen ? first : Verdict::Pass;
}

std::size_t filter(const Policy &policy, std::span<const std::uint32_t> src,
                   std::span<std::uint32_t> out, const FilterOptions &opt, FilterStats &stats) {
    const std::size_t n = src.size();
    std::size_t i = 0;
    while (i < n) {
        const std::uint32_t header = src[i];
        const std::uint32_t type = header >> 30;
        std::uint32_t len = 1;
        if (type == 0 || type == 3) {
            const std::uint32_t count = (header >> 16) & 0x3fff;
            len = count == 0x3fff ? 1 : count + 2;
        } else if (type == 1) {
            len = 1;
        }
        stats.packets++;
        stats.dwords += len;
        if (i + len > n) {
            // A packet running past the end: NOP the remainder, the CP must not read past it.
            stats.truncated++;
            for (std::size_t k = i; k < n; ++k) out[k] = kNop;
            stats.dwords_dropped += n - i;
            i = n;
            break;
        }
        Verdict v = policy.packet(&src[i], len);
        const auto opcode3 = static_cast<std::uint8_t>((header >> 8) & 0xff);
        if (type == 3 && v != Verdict::Drop) {
            if (opt.drop_draws && is_draw_or_dispatch(opcode3)) {
                v = Verdict::Drop;
            } else if (!opt.extra_drop.empty() &&
                       std::find(opt.extra_drop.begin(), opt.extra_drop.end(), opcode3) !=
                           opt.extra_drop.end()) {
                v = Verdict::Drop;
                stats.extra_drops++;
            } else if (opt.mapped) {
                for (const auto &[a, bytes] : memory_operands(&src[i], len)) {
                    if (!opt.mapped(a, bytes == 0 ? 4 : bytes)) {
                        v = Verdict::Drop;
                        stats.unmapped_drops++;
                        break;
                    }
                }
            }
        }
        switch (v) {
        case Verdict::Drop:
            for (std::uint32_t k = 0; k < len; ++k) out[i + k] = kNop;
            stats.dropped++;
            stats.dwords_dropped += len;
            break;
        case Verdict::Pass:
        case Verdict::Rewrite:
        case Verdict::Split: {
            for (std::uint32_t k = 0; k < len; ++k) out[i + k] = src[i + k];
            if (v == Verdict::Pass) stats.passed++;
            else if (v == Verdict::Rewrite) stats.rewritten++;
            else stats.split++;
            if (type != 3) break;
            const auto opcode = static_cast<std::uint8_t>((header >> 8) & 0xff);
            if (opcode == kOpContextControl && opt.safe_context_control && len >= 3 &&
                (out[i + 1] != 0x80000000u || out[i + 2] != 0x80000000u)) {
                out[i + 1] = 0x80000000u;
                out[i + 2] = 0x80000000u;
                stats.context_control_rewrites++;
            }
            if ((opcode == kOpReleaseMem || opcode == kOpEventWriteEop) && opt.clear_int_sel &&
                len >= 4) {
                // RELEASE_MEM: data_cntl is dword 2; EVENT_WRITE_EOP: dword 3. INT_SEL = bits 25:24.
                const std::uint32_t dc = opcode == kOpReleaseMem ? 2u : 3u;
                if ((out[i + dc] & (3u << 24)) != 0) {
                    out[i + dc] &= ~(3u << 24);
                    stats.int_sel_rewrites++;
                }
            }
            std::uint32_t base = 0;
            if (is_plain_set(opcode, base) && len >= 3) {
                const std::uint32_t offset = src[i + 1] & 0xffff;
                for (std::uint32_t k = 0; k + 2 < len; ++k) {
                    const std::uint32_t mm = base + offset + k;
                    if (policy.reg(mm) != Verdict::Rewrite) continue;
                    std::uint32_t &val = out[i + 2 + k];
                    switch (mm) {
                    case kMmComputeStaticThreadMgmtSe0:
                    case kMmComputeStaticThreadMgmtSe1:
                    case kMmComputeStaticThreadMgmtSe2:
                    case kMmComputeStaticThreadMgmtSe3:
                        val &= opt.cu_mask;
                        stats.cu_mask_rewrites++;
                        break;
                    case kMmSpiShaderPgmRsrc3Ps:
                    case kMmSpiShaderPgmRsrc3Vs:
                    case kMmSpiShaderPgmRsrc3Gs:
                    case kMmSpiShaderPgmRsrc3Hs:
                        val = (val & ~0xffffu) | (val & opt.cu_mask & 0xffffu); // CU_EN bits 15:0
                        stats.cu_mask_rewrites++;
                        break;
                    default: break; // a rewrite the table names but the filter does not know
                    }
                }
            }
            break;
        }
        }
        i += len;
    }
    return i;
}

} // namespace bc5::policy
